seed_everything: 0

data:
  h5_path: dataset/cov.h5
  batch_size: 30
  num_workers: 4

model:
  class_path: fpha_spdnet.models.SPDNet
  init_args:
    matrix_size: 63
    num_spatials: [53, 43, 33]
    num_classes: 45
    eps: 1e-5
    use_batch_norm: true

trainer:
  max_epochs: 1500
  accelerator: cpu
  devices: 1
  logger:
    class_path: lightning.pytorch.loggers.csv_logs.CSVLogger
    init_args:
      save_dir: logs
      name: spdnet-bn
      version: reproduction
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val_accuracy
        mode: max
        save_top_k: 1
        filename: weight-{epoch:03d}
        dirpath: logs/spdnet-bn/reproduction

optimizer:
  class_path: geoopt.optim.RiemannianAdam
  init_args:
    lr: 1e-2
